name: E2E Test with tune api

on:
  pull_request:
    paths-ignore:
      - "pkg/ui/v1beta1/frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}
      
      - name: Setup Minikube Cluster
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-minikube.sh

      - name: Setup Katib
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh

      - name: Run E2E Experiment
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-tune-api.sh

    strategy:
      fail-fast: false
      matrix:
        # Detail: https://hub.docker.com/r/kindest/node
        kubernetes-version: ["v1.27.11", "v1.28.7", "v1.29.2"]
